### ISSUE TITLE
Activating HTML5 controls can cause backward navigation

### ISSUE THREAD

**Issue by rkwright** [readium/r2-testapp-swift#8]
Clicking on some HTML5 forms control (e.g. checkbox, video control, etc.) often (but not always) causes the application to navigate backwards one page, i.e. going to the previous page.  This can be seen easily in [EPUB TestSuite 102](http://epubtest.org/epubs/epub30-test-0102-20160116.epub).  For example, tests inout-100 and input-110 are simple checkbox and radio-button tests.  The controls render fine, but clicking on them almost always causes the app to navigate to the previous page.

*Procedure:*
1. Open the test file (see above)
2. Navigate to page with input-100
3. Click on the check-box
4. App goes to previous page.

*Test Environment:*
iPad 5, 16 GB
iOS 11.0.3
R2 Test App 0.2 (2)

**Comment by JayPanoz** [comment]
From issue #1, here’s a list of the results I could get with form elements: 

- buttons and sliders (range) are currently A-OK;
- checkboxes and radio buttons are KO;
- text inputs (including textarea) are KO (and the keyboard won’t show up);
- option/select are KO.

**Comment by iaomw** [comment]
There are more than one bug from`touchHandling.js`. And the logic in JavaScript is too simple, 

Even if you are touching on some components, it will be treated as background touch, then it will also trigger the leftTapped, so it will slide to previous page. That's how does it happen.

Since most of the touch events were treated as background touch, it's not surprise the keyboard never shown up.

**Comment by HadrienGardeur** [comment]
All of these JS resources are meant to be replaced by r2-glue-js at some point, but in the meantime we can ignore additional events based on the nature of the element being tapped.

**Comment by aferditamuriqi** [comment]
I am closing this since this has been already completed and has a merged PR

**Comment by rkwright** [comment]
Unfortunately, I can easily reproduce this with build 1.0.3 (from app store).

#### Steps to reproduce:
1. [Download EPUBTEST 0100 - Reflowable Content Tests](http://epubtest.org/epubs/epub30-test-0100-20160116.epub)
2. Open in the app
3. Navigate to the audio and video tests.  
4. Click the buttons.  

The audio and video play correctly, but frequently (but not always) the app navigates backwards one page.

**Comment by iaomw** [comment]
Thanks. It's obvious the `audio` and `video` are different from `input`. 

The previous fix stopped event pop for `input` as the bug reported, so the `input` element get focus instead of the background. As the consequence, it will not scroll left.  That's also minimum change in the JS code.

Today you reported `audio` and `video`. It could be simply solved by the logic above.But it might be a endless dark hole.  Are there any list for all the interactive elements need taking care?
There are 3 possible solutions:

- If the list is not long, it could be solved by the same solution.
- There may be another better way to solve the touch issue for background and element, this bug should be solved by some JS developer instead of me.
- The new JavaScript library `glue.js.  Is that still under development or finished? 


If we cond

**Comment by mmenu-mantano** [comment]
For reference, the touch handling code for Swift is now in `r2-navigator-swift/gestures.js` ( https://github.com/readium/r2-navigator-swift/blob/develop/r2-navigator-swift/EPUB/Resources/gestures.js ).

A few more interactive elements are supported, but there are still some issues remaining, reported by Jiminy here https://github.com/readium/r2-navigator-swift/issues/55#issuecomment-496144422
